var canvas = document.getElementById('myCanvas');
canvas.width = document.getElementById('myCanvas').clientWidth;
canvas.height = document.getElementById('myCanvas').clientHeight;
var context = canvas.getContext('2d');
context.fillStyle = 'orange';
context.fillRect(175, 100, 100, 100);
context.beginPath();
context.moveTo(0, 300);
context.lineTo(450, 0);
context.strokeStyle = 'red';
context.stroke();