var canvas = document.getElementById('myCanvas');
var context = canvas.getContext('2d');
context.fillStyle = 'orange';
context.fillRect(88, 50, 100, 50);
context.beginPath();
context.moveTo(15,17);
context.lineTo(55,80);
context.strokeStyle='blue';
context.stroke();
context.beginPath();
context.moveTo(0,150);
context.lineTo(300,0);
context.strokeStyle='red';
context.stroke();